### ISSUE TITLE
Error when creating the image

### ISSUE THREAD

**Issue by haraldaarz** [c-sh0/santacruz#1]
Hi!

I have tried to run your docker setup on 2 different machines now, and they both run into the same error message. 
The error occures when I run "docker-compose up -d elasticsearch && docker logs elasticsearch --follow" 

Creating elasticsearch ...

ERROR: for elasticsearch  "host" network_mode is incompatible with port_bindings

ERROR: for elasticsearch  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 564, in execute_convergence_plan
  File "compose/service.py", line 480, in _execute_convergence_create
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 478, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 941, in _get_container_create_options
  File "compose/service.py", line 1073, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[24502] Failed to execute script docker-compose

**Comment by c-sh0** [comment]
That error is from your docker-compose installation. 
https://github.com/docker/compose/issues/8326 
 
 Works fine for me 
 $ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
OS: 
CentOS Linux release 7.7.1908 (Core)
